AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  streaming-lambda

  Sample SAM Template for streaming-lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 29
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  FirstStreamingLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      MemorySize: 1024
      Environment:
        Variables:
          MY_AWS_ACCESS_KEY: ''
          MY_AWS_SECRET_KEY: ''
          MY_BUCKET_NAME: ''
      Policies:
      - Statement:
        - Sid: S3PutObjectPolicy
          Effect: Allow
          Action:
          - s3:PutObject
          Resource: '*'
        - Sid: S3GetObjectPolicy
          Effect: Allow
          Action:
          - s3:GetObject
          Resource: '*'
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        FirstStreaming:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /first-streaming-lambda
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  MyFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref FirstStreamingLambda
      AuthType: AWS_IAM
      InvokeMode: RESPONSE_STREAM

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StreamingApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Streaming/"
  FirstStreamingFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FirstStreamingLambda.Arn
  StreamingFunctionURL:
    Description: "Streaming Lambda Function URL"
    Value: !GetAtt MyFunctionUrl.FunctionUrl
# FirstStreamingLambdaIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt FirstStreamingLambdaRole.Arn
